/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Menu */

#ifndef _Included_Menu
#define _Included_Menu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Menu
 * Method:    inDLL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Menu_inDLL (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
